In [1]:
import polars as pl
import pandas as pd
import glob

In [2]:
RUTA_SII = "data/base_de_datos_facturas/SII/"

In [13]:
df_SII_registro = pl.read_csv(
    f"{RUTA_SII}/*_REGISTRO*.csv",
    truncate_ragged_lines=True,
    separator=";",
    dtypes={
        "Codigo Otro Impuesto": pl.Int32,
        "Valor Otro Impuesto": pl.Int32,
        "Tasa Otro Impuesto": pl.Int32,
        "Fecha Docto": pl.Date
    },
)

df_SII_reclamado = pl.read_csv(
    f"{RUTA_SII}/*_RECLAMADO*.csv",
    truncate_ragged_lines=True,
    separator=";",
    dtypes={
        "Codigo Otro Impuesto": pl.Int32,
        "Valor Otro Impuesto": pl.Int32,
        "Tasa Otro Impuesto": pl.Int32,
        "IVA uso Comun": pl.Int32,
    },
)

In [14]:
df_SII_registro

shape: (72_552, 27)
┌──────┬──────────┬────────────┬────────────┬───┬────────────┬────────────┬────────────┬───────────┐
│ Nro  ┆ Tipo Doc ┆ Tipo       ┆ RUT        ┆ … ┆ NCE o NDE  ┆ Codigo     ┆ Valor Otro ┆ Tasa Otro │
│ ---  ┆ ---      ┆ Compra     ┆ Proveedor  ┆   ┆ sobre      ┆ Otro       ┆ Impuesto   ┆ Impuesto  │
│ i64  ┆ i64      ┆ ---        ┆ ---        ┆   ┆ Fact. de   ┆ Impuesto   ┆ ---        ┆ ---       │
│      ┆          ┆ str        ┆ str        ┆   ┆ Compra     ┆ ---        ┆ i32        ┆ i32       │
│      ┆          ┆            ┆            ┆   ┆ ---        ┆ i32        ┆            ┆           │
│      ┆          ┆            ┆            ┆   ┆ i64        ┆            ┆            ┆           │
╞══════╪══════════╪════════════╪════════════╪═══╪════════════╪════════════╪════════════╪═══════════╡
│ 1    ┆ 33       ┆ Del Giro   ┆ 96689310-9 ┆ … ┆ 0          ┆ null       ┆ null       ┆ null      │
│ 2    ┆ 61       ┆ Del Giro   ┆ 76669630-9 ┆ … ┆ 0          ┆ null       ┆ null       ┆ null      │
│ 3    ┆ 61       ┆ Del Giro   ┆ 76669630-9 ┆ … ┆ 0          ┆ null       ┆ null       ┆ null      │
│ 4    ┆ 61       ┆ Del Giro   ┆ 81698900-0 ┆ … ┆ 0          ┆ null       ┆ null       ┆ null      │
│ …    ┆ …        ┆ …          ┆ …          ┆ … ┆ …          ┆ …          ┆ …          ┆ …         │
│ 1001 ┆ 61       ┆ Del Giro   ┆ 99573490-7 ┆ … ┆ 0          ┆ null       ┆ null       ┆ null      │
│ 1002 ┆ 61       ┆ Del Giro   ┆ 76150425-8 ┆ … ┆ 0          ┆ null       ┆ null       ┆ null      │
│ 1003 ┆ 61       ┆ Del Giro   ┆ 78083940-6 ┆ … ┆ 0          ┆ null       ┆ null       ┆ null      │
│ 1004 ┆ 61       ┆ Del Giro   ┆ 77012870-6 ┆ … ┆ 0          ┆ null       ┆ null       ┆ null      │
└──────┴──────────┴────────────┴────────────┴───┴────────────┴────────────┴────────────┴───────────┘

In [4]:
archivos_SII = glob.glob(f"{RUTA_SII}/*.csv")
archivos_SII_registro = list(filter(lambda x: "REGISTRO" in x, archivos_SII))
archivos_SII_reclamado = list(filter(lambda x: "RECLAMADO" in x, archivos_SII))
archivos_SII_pendiente = list(filter(lambda x: "PENDIENTE" in x, archivos_SII))
archivos_SII_no_incluir = list(filter(lambda x: "NO_INCLUIR" in x, archivos_SII))

In [9]:
df_SII_registro = pd.concat((pd.read_csv(archivo, sep=";", index_col=False) for archivo in archivos_SII_registro))
df_SII_reclamado = pd.concat((pd.read_csv(archivo, sep=";") for archivo in archivos_SII_reclamado))
df_SII_pendiente = pd.concat((pd.read_csv(archivo, sep=";") for archivo in archivos_SII_pendiente))
df_SII_no_incluir = pd.concat((pd.read_csv(archivo, sep=";") for archivo in archivos_SII_no_incluir))

C:\Users\ppizarro\AppData\Local\Temp\ipykernel_13160\694734670.py:3: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_SII_pendiente = pd.concat((pd.read_csv(archivo, sep=";") for archivo in archivos_SII_pendiente))

In [10]:
df_SII_registro

,Nro,Tipo Doc,Tipo Compra,RUT Proveedor,Razon Social,Folio,Fecha Docto,Fecha Recepcion,Fecha Acuse,Monto Exento,...,IVA uso Comun,Impto. Sin Derecho a Credito,IVA No Retenido,Tabacos Puros,Tabacos Cigarrillos,Tabacos Elaborados,NCE o NDE sobre Fact. de Compra,Codigo Otro Impuesto,Valor Otro Impuesto,Tasa Otro Impuesto
0,1.0,33,Del Giro,96689310-9,TRANSBANK S.A.,22273615,08/06/2017,28/06/2017 10:51:06,NaN,0.0,...,NaN,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN
1,2.0,61,Del Giro,76669630-9,OPKO CHILE S.A.,25140,23/06/2017,23/06/2017 08:37:58,NaN,0.0,...,NaN,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN
2,3.0,61,Del Giro,76669630-9,OPKO CHILE S.A.,25141,23/06/2017,23/06/2017 08:43:22,NaN,0.0,...,NaN,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN
3,4.0,61,Del Giro,81698900-0,Pont. Universidad Catolica de Chile,15708,27/06/2017,27/06/2017 14:03:42,NaN,81256.0,...,NaN,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN
4,5.0,61,Del Giro,93745000-1,JOHNSON JOHNSON DE CHILE S.A.,93123,23/06/2017,27/06/2017 16:05:53,NaN,0.0,...,NaN,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999,1000.0,61,Del Giro,99576080-0,SUR MEDICAL SPA,3633,27/03/2023,27/03/2023 15:10:09,NaN,0.0,...,NaN,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN
1000,1001.0,61,Del Giro,99573490-7,UC CHRISTUS SERVICIOS CLÍNICOS S.A,63448,22/03/2023,30/03/2023 12:51:44,NaN,3511668.0,...,NaN,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN
1001,1002.0,61,Del Giro,76150425-8,COMERCIAL REUTTER S.A.,11666,30/03/2023,30/03/2023 14:53:49,NaN,0.0,...,NaN,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN
1002,1003.0,61,Del Giro,78083940-6,IMH S.A.,1265,31/03/2023,31/03/2023 10:23:24,NaN,0.0,...,NaN,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN
1003,1004.0,61,Del Giro,77012870-6,Comercial Red Office Ltda.,37549,31/03/2023,31/03/2023 16:22:10,NaN,0.0,...,NaN,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN

In [ ]:
df_SII_registro = pl.read_csv(
    "data/base_de_datos_facturas/SII/RCV_COMPRA_NO_INCLUIR_61608402-K_201808.csv",
    separator=";",
    encoding="latin-1", truncate_ragged_lines=True
)

In [ ]:
df_SII_reclamado = pl.concat((pl.read_csv(archivo, separator=";", truncate_ragged_lines=True) for archivo in archivos_SII_reclamado))

ShapeError: unable to vstack, dtypes for column "Codigo Otro Impuesto" don't match: `str` and `i64`

# SII

In [ ]:
COLS_SII_UTILIZADAS = [
    "Tipo Doc",
    "RUT Emisor",
    "Razon Social",
    "Folio",
    "Fecha Docto",
    "Fecha Recepcion",
    "Fecha Reclamo",
    "Fecha Acuse" "Monto Exento",
    "Monto Neto",
    "Monto IVA Recuperable",
    "Monto Total",
]

schema = {
    "Nro": pl.Int64,
    "Tipo Doc": pl.Int64,
    "Tipo Compra": pl.Utf8,
    "RUT Proveedor": pl.Utf8,
    "Razon Social": pl.Utf8,
    "Folio": pl.Int64,
    "Fecha Docto": pl.Utf8,
    "Fecha Recepcion": pl.Utf8,
    "Fecha Acuse": pl.Utf8,
    "Monto Exento": pl.Int64,
    "Monto Neto": pl.Int64,
    "Monto IVA Recuperable": pl.Int64,
    "Monto Iva No Recuperable": pl.Int64,
    "Codigo IVA No Rec.": pl.Int64,
    "Monto Total": pl.Int64,
    "Monto Neto Activo Fijo": pl.Int64,
    "IVA Activo Fijo": pl.Int64,
    "IVA uso Comun": pl.Int64,
    "Impto. Sin Derecho a Credito": pl.Int64,
    "IVA No Retenido": pl.Int64,
    "NCE o NDE sobre Fact. de Compra": pl.Int64,
    "Codigo Otro Impuesto": pl.Utf8,
    "Valor Otro Impuesto": pl.Utf8,
    "Tasa Otro Impuesto": pl.Utf8,
}

df = (
    pl.scan_csv("crudos/base_de_datos_facturas/SII/*.csv", separator=";", dtypes=schema)
    .rename({"RUT Proveedor": "RUT Emisor"})
    .with_columns(
        pl.when((pl.col("Tipo Doc") == 61) | (pl.col("Tipo Doc") == 56)).then(
            pl.col(["Monto Exento", "Monto Neto", "Monto IVA Recuperable", "Monto Total"]) * -1
        )
    )
    .with_columns(pl.concat_str(pl.col(["RUT Emisor", "Folio"])).alias("llave_id"))
)

In [ ]:
df.collect()

ComputeError: found more fields than defined in 'Schema'

Consider setting 'truncate_ragged_lines=True'.